// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/v1/admin/stats`
 */
export type AdminStats = { users: number, groups: number, messages: number, sessions: number, attachments_bytes: number, online_users: number, };
