// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uniform error body for all non-2xx API responses.
 */
export type ApiError = { 
/**
 * Stable machine-readable code, e.g. "invalid_credentials", "not_a_member".
 */
code: string, message: string, };
