// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One merged batch of local Yjs edits (update v1, base64). Clients batch to
 * ≤ 192 KiB; the server accepts up to 4 MiB (413 `update_too_large` above).
 */
export type AppendUpdateRequest = { update_b64: string, };
