// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One merged batch of local Yjs edits (update v1, base64, ≤ 256 KB).
 */
export type AppendUpdateRequest = { update_b64: string, };
