// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentId } from "./AttachmentId";

export type AttachmentMeta = { id: AttachmentId, mime: string, byte_size: number, original_name: string | null, };
