// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ephemeral cursor/selection presence (y-protocols awareness, base64).
 */
export type AwarenessRequest = { data_b64: string, };
