// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasBoard } from "./CanvasBoard";
import type { CanvasElement } from "./CanvasElement";

export type BoardDetail = { board: CanvasBoard, elements: Array<CanvasElement>, };
