// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

/**
 * One element on a board. `kind` is one of: `sticky`, `text`, `frame`,
 * `connector`. Connectors ignore x/y/w/h and reference two other elements.
 */
export type CanvasElement = { id: number, board_id: number, kind: string, x: number, y: number, w: number, h: number, 
/**
 * Stacking order; higher renders on top.
 */
z: number, text: string, 
/**
 * Sticky color key (e.g. "yellow"); empty for other kinds.
 */
color: string, 
/**
 * Text styling JSON (size/bold/italic/underline/align/list); empty = defaults.
 */
style: string, from_id: number | null, to_id: number | null, updated_by: UserId, updated_at: number, };
