// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { MessageId } from "./MessageId";

/**
 * One row of `GET /api/v1/me/reads`: where the caller's read marker sits in
 * a channel, plus how many later messages from OTHERS are waiting.
 */
export type ChannelRead = { channel_id: ChannelId, last_read_message_id: MessageId, unread_count: number, updated_at: number, };
