// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { ChannelKind } from "./ChannelKind";
import type { GroupId } from "./GroupId";

export type Channel = { id: ChannelId, group_id: GroupId | null, kind: ChannelKind, name: string | null, position: number, };
