// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * client → server frames.
 */
export type ClientFrame = { "op": "auth", "d": { token: string, protocol_version: number, } } | { "op": "sub", "d": { rooms: Array<string>, } } | { "op": "unsub", "d": { rooms: Array<string>, } } | { "op": "ping", "d": { client_time: number, } };
