// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateInviteRequest = { 
/**
 * Seconds until expiry; None = never expires.
 */
expires_in_seconds: number | null, max_uses: number | null, };
