// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentId } from "./AttachmentId";

export type CreateEmoteRequest = { name: string, attachment_id: AttachmentId, };
