// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateElementRequest = { kind: string, 
/**
 * Page to place it on; omitted means the board's first page.
 */
page: number | null, x: number, y: number, w: number, h: number, text: string, color: string, style: string, from_id: number | null, to_id: number | null, };
