// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateElementRequest = { kind: string, x: number, y: number, w: number, h: number, text: string, color: string, from_id: number | null, to_id: number | null, };
