// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";

export type CreateSessionRequest = { channel_id: ChannelId, title: string, };
