// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreatePromptRequest = { prompt_doc: JsonValue, timer_seconds: number | null, };
