// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateThreadRequest = { content: string, anchor_b64: string | null, head_b64: string | null, excerpt: string | null, };
