// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A device row from `auth_sessions` (token never leaves the server).
 */
export type DeviceSession = { id: number, device_label: string | null, created_at: number, last_seen_at: number, 
/**
 * True for the session making this request.
 */
current: boolean, };
