// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { UserRef } from "./UserRef";

/**
 * A DM conversation: the channel plus who it's with.
 */
export type DmChannel = { channel_id: ChannelId, peer: UserRef, };
