// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRef } from "./UserRef";

export type Document = { id: number, owner: UserRef, title: string, 
/**
 * `none` | `screenplay` | `stageplay` | `manuscript` | `poetry`.
 */
format: string, created_at: number, updated_at: number, };
