// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentVersionMeta } from "./DocumentVersionMeta";

export type DocumentVersion = { meta: DocumentVersionMeta, doc_json: string, };
