// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Document } from "./Document";

/**
 * Detail for opening: compacted Yjs state (update v1, base64) current
 * through `seq`; apply then subscribe to `document:{id}` for live updates.
 */
export type DocumentDetail = { document: Document, 
/**
 * `owner` | `write` | `read`.
 */
my_access: string, state_b64: string, seq: number, };
