// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRef } from "./UserRef";

export type DocumentVersionMeta = { id: number, doc_id: number, 
/**
 * `auto` | `named` | `draft`.
 */
kind: string, name: string | null, changed_blocks: number, added_words: number, removed_words: number, created_by: UserRef, created_at: number, };
