// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Document } from "./Document";

/**
 * List entry: a document plus the caller's access to it.
 */
export type DocumentListItem = { document: Document, 
/**
 * `owner` | `write` | `read`.
 */
my_access: string, };
