// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRef } from "./UserRef";

export type DocumentThreadMessage = { id: number, thread_id: number, author: UserRef, content: string, created_at: number, };
