// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentThreadMessage } from "./DocumentThreadMessage";
import type { UserRef } from "./UserRef";

/**
 * A feedback thread: root comment plus replies, optionally anchored to a
 * text selection via Yjs relative positions (base64) with a plain-text
 * excerpt kept for when the referenced text later changes.
 */
export type DocumentThread = { id: number, doc_id: number, author: UserRef, anchor_b64: string | null, head_b64: string | null, excerpt: string | null, resolved: boolean, created_at: number, messages: Array<DocumentThreadMessage>, };
