// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRef } from "./UserRef";

export type DocumentActivity = { id: number, doc_id: number, kind: string, actor: UserRef, subject_kind: string | null, subject_id: number | null, subject_name: string | null, detail: string | null, created_at: number, };
