// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocumentShare = { doc_id: number, 
/**
 * `user` | `group`.
 */
subject_kind: string, subject_id: number, 
/**
 * Display name of the user or group, for share lists.
 */
subject_name: string, 
/**
 * `read` | `write`.
 */
access: string, created_at: number, };
