// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentUpdateRow } from "./DocumentUpdateRow";

/**
 * Catch-up tail from `GET /documents/{id}/updates?since=N`. `truncated`
 * means rows before the requested point were compacted away — reload the
 * full document state instead of applying the tail.
 */
export type DocumentUpdateBatch = { updates: Array<DocumentUpdateRow>, truncated: boolean, };
