// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A personal folder for organizing one's own documents (flat, per-user).
 */
export type DocumentFolder = { id: number, name: string, document_count: number, created_at: number, };
