// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentId } from "./AttachmentId";
import type { GroupId } from "./GroupId";

export type Emote = { id: number, group_id: GroupId, name: string, attachment_id: AttachmentId, };
