// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRef } from "./UserRef";

export type FriendRequest = { id: number, from: UserRef, to: UserRef, created_at: number, };
