// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRef } from "./UserRef";

export type Friend = { user: UserRef, since: number, 
/**
 * Live at request time; deltas arrive as `presence.update` on `user:{me}`.
 */
online: boolean, 
/**
 * "online" | "busy" when online, None when offline (or hidden).
 */
status: string | null, };
