// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendRequest } from "./FriendRequest";

export type FriendRequests = { incoming: Array<FriendRequest>, outgoing: Array<FriendRequest>, };
