// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { GroupRole } from "./GroupRole";
import type { UserId } from "./UserId";

export type Group = { id: GroupId, name: string, owner_id: UserId, my_role: GroupRole, created_at: number, };
