// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/v1/healthz`
 */
export type Healthz = { ok: boolean, server_name: string, protocol_version: number, server_time: number, };
