// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Invite = { code: string, expires_at: number | null, max_uses: number | null, use_count: number, revoked: boolean, };
