// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/v1/link-preview?url=` — server-fetched page metadata for canvas
 * link cards. Fields are None when the page is unreachable or opaque.
 */
export type LinkPreview = { url: string, title: string | null, description: string | null, image_url: string | null, };
