// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginRequest = { username: string, password: string, 
/**
 * Free-form label shown in the user's session list, e.g. "MacBook Pro".
 */
device_label: string | null, };
