// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "./MessageId";

/**
 * `PUT /api/v1/channels/{id}/read` — advance the caller's read marker.
 * Forward-only: an older id than the stored marker is ignored.
 */
export type MarkReadRequest = { message_id: MessageId, };
