// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupRole } from "./GroupRole";
import type { UserRef } from "./UserRef";

export type Member = { user: UserRef, role: GroupRole, joined_at: number, };
