// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One emoji's reaction tally on a message.
 */
export type MessageReaction = { emoji: string, count: number, 
/**
 * Whether the requesting user is among the reactors.
 */
me: boolean, 
/**
 * Display names of reactors, for the hover tooltip (capped server-side).
 */
users: Array<string>, };
