// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Move a document into a folder (`null` = out of any folder).
 */
export type MoveDocumentRequest = { folder_id: number | null, };
