// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

/**
 * Online user ids for a group (REST snapshot; deltas arrive via
 * `presence.update` WS events).
 */
export type PresenceSnapshot = { online: Array<UserId>, };
