// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WritingSessionId } from "./WritingSessionId";

/**
 * Payload for `prompt.started` events in room `session:{id}`. A session
 * holds multiple prompts; timers are per prompt.
 */
export type PromptStarted = { session_id: WritingSessionId, 
/**
 * Row id in `session_prompts`.
 */
prompt_id: number, started_at: number, 
/**
 * Absent when the prompt has no timer.
 */
ends_at: number | null, };
