// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A freshly generated reset code — shown to the admin exactly once.
 */
export type ResetCodeResponse = { code: string, expires_at: number, };
