// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Redeem an admin-issued one-time reset code for a new password.
 */
export type ResetPasswordRequest = { username: string, code: string, new_password: string, };
