// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { GroupId } from "./GroupId";
import type { MessageId } from "./MessageId";
import type { UserRef } from "./UserRef";

/**
 * One `GET /api/v1/messages/search` hit. `snippet` is plain text with
 * matches wrapped in `<<` `>>` markers — never HTML.
 */
export type SearchHit = { message_id: MessageId, channel_id: ChannelId, group_id: GroupId | null, channel_name: string | null, author: UserRef, snippet: string, created_at: number, };
