// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentId } from "./AttachmentId";
import type { MessageId } from "./MessageId";

export type SendMessageRequest = { content: string, reply_to_id: MessageId | null, attachment_ids: Array<AttachmentId>, };
