// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/v1/identity` — unauthenticated server identity for TOFU pinning.
 */
export type ServerIdentity = { server_name: string, 
/**
 * ML-DSA-65 public key, base64url.
 */
mldsa_pubkey: string, 
/**
 * ML-DSA signature over `"writform-cert-binding-v1" || SHA-256(cert SPKI)`, base64url.
 */
cert_binding_sig: string, };
