// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { PongData } from "./PongData";
import type { ReadyData } from "./ReadyData";

/**
 * server → client frames. `room` is present on fan-out events.
 */
export type ServerFrame = { "ev": "ready", d: ReadyData, } | { "ev": "pong", d: PongData, } | { "ev": "event", room: string, kind: string, data: JsonValue, } | { "ev": "error", code: string, message: string, };
