// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionPrompt } from "./SessionPrompt";
import type { Submission } from "./Submission";
import type { WritingSession } from "./WritingSession";

export type SessionDetail = { session: WritingSession, prompts: Array<SessionPrompt>, 
/**
 * All submissions for ended prompts; only the caller's own for
 * running/draft prompts (no peeking mid-write).
 */
submissions: Array<Submission>, };
