// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/v1/groups/{id}/join-code` — set (Some) or clear (None) the
 * permanent join code. Normalized like channel names; unique server-wide.
 */
export type SetJoinCodeRequest = { code: string | null, };
