// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetShareRequest = { 
/**
 * `user` | `group`.
 */
subject_kind: string, subject_id: number, 
/**
 * `read` | `write`.
 */
access: string, };
