// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TipTap JSON snapshot for version history. Without `name`, an automatic
 * snapshot (rate-limited and deduplicated); with `name`, always stored.
 */
export type SnapshotRequest = { doc_json: string, name: string | null, };
