// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { UserRef } from "./UserRef";

export type Submission = { id: number, prompt_id: number, author: UserRef, 
/**
 * TipTap JSON document.
 */
doc: JsonValue, updated_at: number, };
