// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update of document metadata (write access required).
 */
export type UpdateDocumentRequest = { title: string | null, format: string | null, };
