// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Board-level settings. Only the background travels here today.
 */
export type UpdateBoardRequest = { style: string, };
