// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentId } from "./AttachmentId";

export type UpdateProfileRequest = { 
/**
 * None clears the display name.
 */
display_name: string | null, 
/**
 * None clears the avatar; the attachment must be the caller's upload.
 */
avatar_attachment_id: AttachmentId | null, 
/**
 * None clears the banner; the attachment must be the caller's upload.
 */
banner_attachment_id: AttachmentId | null, 
/**
 * `#rrggbb`, or None for the default look.
 */
accent_color: string | null, 
/**
 * "About me" shown on the profile card (None clears, max 300 chars).
 */
bio: string | null, };
