// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentId } from "./AttachmentId";

/**
 * `PATCH /api/v1/groups/{id}` (admin only). Icon/color are full replacement
 * (send the current value to keep it); name only changes when Some.
 */
export type UpdateGroupRequest = { name: string | null, icon_attachment_id: AttachmentId | null, accent_color: string | null, };
