// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProfileRequest = { 
/**
 * None clears the display name.
 */
display_name: string | null, };
