// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update; omitted fields keep their value (last write wins).
 */
export type UpdateElementRequest = { 
/**
 * Moves the element to another page.
 */
page: number | null, x: number | null, y: number | null, w: number | null, h: number | null, z: number | null, text: string | null, color: string | null, style: string | null, };
