// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentId } from "./AttachmentId";
import type { UserId } from "./UserId";

/**
 * `GET /api/v1/users/{id}/profile` — the public profile card.
 */
export type UserProfile = { id: UserId, username: string, display_name: string | null, avatar_attachment_id: AttachmentId | null, 
/**
 * Banner image for the card; accent color is the fallback fill.
 */
banner_attachment_id: AttachmentId | null, accent_color: string | null, bio: string | null, 
/**
 * "online" | "busy" when reachable, None when offline (or hidden).
 */
status: string | null, created_at: number, };
