// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentId } from "./AttachmentId";
import type { UserId } from "./UserId";

export type User = { id: UserId, username: string, display_name: string | null, is_server_admin: boolean, avatar_attachment_id: AttachmentId | null, accent_color: string | null, created_at: number, };
