// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { UserId } from "./UserId";

/**
 * Opaque WebRTC signaling payload relayed to one member of the same room.
 */
export type VoiceSignalRequest = { to: UserId, data: JsonValue, };
