// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRef } from "./UserRef";

/**
 * Returned from join: everyone already in the room (the joiner initiates a
 * peer connection to each of them).
 */
export type VoiceJoinResponse = { participants: Array<UserRef>, };
