// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRef } from "./UserRef";
import type { VoiceChannel } from "./VoiceChannel";

export type VoiceChannelInfo = { channel: VoiceChannel, participants: Array<UserRef>, };
