// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { SessionState } from "./SessionState";
import type { UserRef } from "./UserRef";
import type { WritingSessionId } from "./WritingSessionId";

export type WritingSession = { id: WritingSessionId, 
/**
 * The group channel this session was created in.
 */
channel_id: ChannelId, creator: UserRef, title: string, state: SessionState, 
/**
 * Side-chat channel (kind = session), auto-created with the session.
 */
chat_channel_id: ChannelId, created_at: number, ended_at: number | null, };
